# Generated by Django 3.2.8 on 2021-10-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
    ]
