# Generated by Django 3.2.9 on 2021-11-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_userprofile_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activate_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Код активации'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activate_key_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
