# Generated by Django 3.2.9 on 2021-11-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20211120_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, verbose_name='Возраст'),
        ),
    ]
