# Generated by Django 3.2.9 on 2021-11-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20211123_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский'), ('O', 'Другое')], default='O', max_length=1, verbose_name='Пол'),
        ),
    ]
